server:
  port: 8081

# Настройка базы данных
# Укажите параметры url, username и password в переменных среды IDE или секретных ключах на GitHub/GitLab для CI/CD
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: validate

# Настройка новых приложений и правил валидации
# После new-applications укажите желаемое имя нового приложения и желаемые поля для проверки
# Все возможные варианты полей указаны в примере тестового приложения test-app-all-fields
# Примеры частичной проверки полей можно посмотреть в разделе test-app-part-fields
application:
  new-applications:
    test-app-all-fields:
      - bank-id
      - lastname
      - firstname
      - middle-name
      - birth-date
      - passport-number
      - birth-place
      - phone-number
      - email
      - registration-address
      - residential-address
    test-app-part-fields:
      - phone-number
      - email