server:
  port: 8081

# Настройка базы данных
# Укажите параметры url, username и password в переменных среды IDE или секретных ключах на GitHub/GitLab для CI/CD
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: validate

# Настройка новых приложений и правил валидации
# После new-applications укажите желаемое имя нового приложения и желаемые поля для проверки
# Все возможные варианты полей указаны в примере тестового приложения all
# Примеры частичной проверки полей можно посмотреть в разделе part
# Обратите внимание: название приложения должно состоять из одного слова, написанного в нижнем регистре
application:
  new-applications:
    all:
      - bankId
      - lastname
      - firstname
      - middleName
      - birthDate
      - passportNumber
      - birthPlace
      - phoneNumber
      - email
      - registrationAddress
      - residentialAddress
    part:
      - phoneNumber
      - email